# Generated by Django 5.1.1 on 2024-10-04 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experiences",
            fields=[
                ("experiences_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=800)),
                ("description", models.TextField(blank=True, null=True)),
                ("organization", models.CharField(max_length=300)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField(blank=True, null=True)),
                (
                    "experience_type",
                    models.CharField(
                        choices=[
                            ("DIP", "Diploma"),
                            ("EXP", "Experience"),
                            ("ART", "Article"),
                            ("OTH", "Other"),
                        ],
                        default="DIP",
                        max_length=3,
                    ),
                ),
                ("diploam_url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("project_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
