# Generated by Django 5.1.1 on 2024-10-01 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="blog_entry",
            fields=[
                ("blog_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("github_url", models.URLField(blank=True, null=True)),
                ("external_url", models.URLField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
