# Generated by Django 5.1.1 on 2025-02-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_project_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('content', models.TextField()),
                ('image', models.URLField()),
            ],
        ),
    ]
