# Generated by Django 5.1.1 on 2025-02-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
        ('projects', '0002_project_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='skills',
            field=models.ManyToManyField(blank=True, to='projects.skill'),
        ),
    ]
