# Generated by Django 5.1.1 on 2025-02-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('github', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
    ]
